name: pm25
channels:
- defaults
- conda-forge
dependencies:
- ipykernel>=4.6.1
- jupyter>=1.0.0
- numpy>=1.13.3
- pandas>=0.23.4
- python==3.6.9
- seaborn==0.9.0
- spacy==2.2.1
- pip:
  - matplotlib==3.1.1
  - scikit-learn==0.21.3
